// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3D2ixKrruCAoNVCox5Azx5jBoaJ0V4W8',
    appId: '1:3752203337:web:a6992b82b5cfb74d1f1b98',
    messagingSenderId: '3752203337',
    projectId: 'mobilebloodbanks',
    authDomain: 'mobilebloodbanks.firebaseapp.com',
    storageBucket: 'mobilebloodbanks.appspot.com',
    measurementId: 'G-RN66H8EV9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh1iD-AGvpIH35KFQOBb-o0x0BrFxX73g',
    appId: '1:3752203337:android:13239cf5fff228fb1f1b98',
    messagingSenderId: '3752203337',
    projectId: 'mobilebloodbanks',
    storageBucket: 'mobilebloodbanks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_uLc4ITQHQJCYQVrN-WPJHw1DOL04gWY',
    appId: '1:3752203337:ios:0abf5af94208aac31f1b98',
    messagingSenderId: '3752203337',
    projectId: 'mobilebloodbanks',
    storageBucket: 'mobilebloodbanks.appspot.com',
    androidClientId: '3752203337-1p3gqv7cpfeh2dhd32p0mjpbmvurvfe6.apps.googleusercontent.com',
    iosClientId: '3752203337-prjrhn12bh8ev8vfj059h6rej92a4bd8.apps.googleusercontent.com',
    iosBundleId: 'me.nafish.mbf',
  );
}
